version: "3.3"
services:
  app:
    build:
      args:
        UID: ${UID-1000}
        GID: ${GID-1000}
      context: ./
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:rw
    networks:
      - laravelLibPayment
networks:
  laravelLibPayment:
    driver: bridge
